name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".next"


[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "towns"
database_id = "ce736757-4c3b-4a7c-8fc8-46e7203d3a82"
