import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeScript } from "@/lib/theme/theme-script";
import { Providers } from "@/lib/theme/provider";
import Nav from "@/components/NextUI/Navigarion/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <head>
        <ThemeScript />
      </head>
      <body className={inter.className}>
        <Providers>
          <Nav>
            {children}
          </Nav>
        </Providers>
      </body>
    </html>
  );
}
